[versions]
kotlin = "1.6.21"
kotest = "5.5.4"

[libraries]
kotest-assertions-shared = { group = "io.kotest", name = "kotest-assertions-shared", version.ref = "kotest" }
kotest-framework-api = { group = "io.kotest", name = "kotest-framework-api", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
gradle-plugin-idea-ext = { group = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext", name = "gradle-idea-ext", version = "1.0" }
gradle-plugin-kotlin-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
kotest = ["kotest-assertions-shared", "kotest-runner-junit5", "kotest-framework-api"]

[plugins]
downloaddependencies = { id = "uk.org.lidalia.downloaddependencies", version = "0.4.0" }
dependencyanalysis = { id = "com.autonomousapps.dependency-analysis", version = "1.18.0" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.13.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.46.0" }
